{% set name = "pyramid_tm" %}
{% set version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8148d2191285280c9a0c23e6df1018b3514b4cef02115b872dd0350a4d78709c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyramid >=1.5
    - transaction >=2.0

test:
  imports:
    - pyramid_tm

about:
  home: https://docs.pylonsproject.org/projects/pyramid_tm
  license: LicenseRef-Pylons
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Pyramid requests joining the Python transaction package'
  description: |
    pyramid_tm is a package which allows Pyramid requests to join the
    active transaction as provided by the Python transaction package.
  doc_url: https://docs.pylonsproject.org/projects/pyramid_tm/
  dev_url: https://github.com/Pylons/pyramid_tm

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
